SELECT DISTINCT A.ID, A.NAME 
FROM (SELECT PLACE_ID ID, NAME FROM PLACES, SCHEDULES WHERE PLACES.ID = SCHEDULES.PLACE_ID AND SCHEDULES.SCHEDULED_AT = TO_DATE('2019-01-06', 'YYYY-MM-DD')) A, PLACE_REVIEWS
WHERE A.ID = PLACE_REVIEWS.PLACE_ID
ORDER BY A.ID;